In [ ]:
# EX 1

In [108]:
# 1.a
import numpy as np
import time
import matplotlib.pyplot as plt

def contraction(G, e):
    
    debut = time.time()
    
    # récupération des indice des deux sommets à fusionner
    x,y = e
    # recupération du nombre d'arêtre entre les deux sommets
    k = G[x,y]
    
    # récupération du nombre d'arête entre y et chaque autre sommet
    fus_l = G[y,:]
    
    #  pour ne pas compter 2 fois les liaisons entre x et y,
    G[x,y] -= k

        
    G[x,:] += fus_l
    G[:,x] += fus_l

    G[y,:] = np.zeros(len(G))
    G[:,y] = np.zeros(len(G))
    
    fin = time.time()
    
    tps = fin-debut
    
    return G, tps, y


In [92]:
# 1.b

G1 = np.array([[1,2,0,1],
     [2,0,3,1],
     [0,3,1,1],
     [1,1,1,0]])

e = [0,1]

#plt.plot(100, log_tps , "r",)
#plt.show()

0.0002669523000717163
0.00025917439460754394


In [98]:
# graph complet
tps_complet = []

for i in range(10000):
    G = np.ones((500,500))
    G_c, tps = contraction(G,e)
    tps_complet.append(tps)
    
tps_complet_2 = []

for i in range(10000):
    G = np.ones((500,500))*2
    G_c, tps = contraction(G,e)
    tps_complet_2.append(tps)

print(np.mean(tps_complet))
print(np.mean(tps_complet_2))

0.00027592294216156004
0.0002731201648712158


In [97]:
tps_cycle = []

for i in range(10000):
    G = np.zeros((500,500))
    np.fill_diagonal(G[:,1:], 1)
    G[-1,0] = 1
    G_c, tps = contraction(G,e)
    tps_cycle.append(tps)
    
print(np.mean(tps_cycle))


[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0.00027569336891174315


In [104]:
tps_proba = []

for i in range(10000):
    G = np.random.randint(2, size = (500,500))
    G_c, tps = contraction(G,e)
    tps_proba.append(tps)
    
print(np.mean(tps_proba))


0.0002736063718795776


In [123]:
def selectRandom(n,S):
    x = np.random.randint(n)
    y = np.random.randint(n)
    
    while (x == y) or (y in S):
        y = np.random.randint(n)
        
    return x,y

In [124]:
def karger(G):
    V = [*range(len(G))]
    print(V)
    S = []
    
    while len(V) > 2:
        e = selectRandom(len(V), S)
        G,tps ,y = contraction(G,e)
        
        print(y,V)
        
        V.remove(y)
        S.append(y)
        
    return S
    

In [125]:
G1 = np.array([[0,1,0,0,0,0],
                [0,0,1,0,1,0],
                [0,1,0,1,1,0],
                [0,0,1,0,0,1],
                [0,1,1,0,0,1],
                [0,0,0,1,1,0]])

print(karger(G1))

[0, 1, 2, 3, 4, 5]
5 [0, 1, 2, 3, 4, 5]
0 [0, 1, 2, 3, 4]
1 [1, 2, 3, 4]
2 [2, 3, 4]
[5, 0, 1, 2]
